# Generated by Django 4.1.1 on 2022-10-04 22:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz_app', '0002_alter_quizparticipant_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quizparticipant',
            unique_together={('user', 'quiz')},
        ),
    ]
