# Generated by Django 4.1.1 on 2022-10-05 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('quiz_app', '0003_alter_quizparticipant_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.question'),
        ),
    ]
