# Generated by Django 4.1.1 on 2022-10-05 01:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('quiz_app', '0004_alter_useranswer_question'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together={('question', 'selected_solution', 'participant')},
        ),
    ]
