# Generated by Django 4.1.2 on 2022-10-14 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('quiz_app', '0009_courseparticipant'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=255)),
                ('size', models.IntegerField()),
                ('order', models.IntegerField()),
                ('data', models.FileField(upload_to='data')),
                ('course_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items',
                                                     to='quiz_app.coursesection')),
            ],
        ),
        migrations.DeleteModel(
            name='SectionItem',
        ),
    ]
