# Generated by Django 4.1.2 on 2022-10-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('quiz_app', '0010_coursesectionitem_delete_sectionitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesectionitem',
            name='data',
            field=models.FileField(null=True, upload_to='data'),
        ),
    ]
