# Generated by Django 4.1.2 on 2022-10-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('quiz_app', '0011_alter_coursesectionitem_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesectionitem',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
