# Generated by Django 4.1.2 on 2022-10-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('quiz_app', '0013_alter_coursesectionitem_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
